"""new fields in user model added

Revision ID: 629100c8f499
Revises: 808c99e666a3
Create Date: 2019-09-05 15:34:10.180285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629100c8f499'
down_revision = '808c99e666a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
